//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 05:08:53 PM IST 
//


package com.privasia.scss.hpat.etp.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ediBookingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ediBookingType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="operation" type="{http://etp.privasia.com/etp/service/schema}operationType"/&gt;
 *         &lt;element name="haulageCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="driverIc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pmHeadNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="trailerNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="truckPlateNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bookingDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bufferTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="trailerType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="containerList" type="{http://etp.privasia.com/etp/service/schema}ediContainersType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ediBookingType", propOrder = {
    "operation",
    "haulageCode",
    "driverIc",
    "pmHeadNo",
    "trailerNo",
    "truckPlateNo",
    "bookingDate",
    "bufferTime",
    "trailerType",
    "containerList"
})
public class EdiBookingType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected OperationType operation;
    @XmlElement(required = true)
    protected String haulageCode;
    @XmlElement(required = true)
    protected String driverIc;
    @XmlElement(required = true)
    protected String pmHeadNo;
    @XmlElement(required = true)
    protected String trailerNo;
    @XmlElement(required = true)
    protected String truckPlateNo;
    @XmlElement(required = true)
    protected String bookingDate;
    @XmlElement(required = true)
    protected String bufferTime;
    @XmlElement(required = true)
    protected String trailerType;
    @XmlElement(required = true)
    protected List<EdiContainersType> containerList;

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link OperationType }
     *     
     */
    public OperationType getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationType }
     *     
     */
    public void setOperation(OperationType value) {
        this.operation = value;
    }

    /**
     * Gets the value of the haulageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaulageCode() {
        return haulageCode;
    }

    /**
     * Sets the value of the haulageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaulageCode(String value) {
        this.haulageCode = value;
    }

    /**
     * Gets the value of the driverIc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverIc() {
        return driverIc;
    }

    /**
     * Sets the value of the driverIc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverIc(String value) {
        this.driverIc = value;
    }

    /**
     * Gets the value of the pmHeadNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmHeadNo() {
        return pmHeadNo;
    }

    /**
     * Sets the value of the pmHeadNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmHeadNo(String value) {
        this.pmHeadNo = value;
    }

    /**
     * Gets the value of the trailerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrailerNo() {
        return trailerNo;
    }

    /**
     * Sets the value of the trailerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrailerNo(String value) {
        this.trailerNo = value;
    }

    /**
     * Gets the value of the truckPlateNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTruckPlateNo() {
        return truckPlateNo;
    }

    /**
     * Sets the value of the truckPlateNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTruckPlateNo(String value) {
        this.truckPlateNo = value;
    }

    /**
     * Gets the value of the bookingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingDate() {
        return bookingDate;
    }

    /**
     * Sets the value of the bookingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingDate(String value) {
        this.bookingDate = value;
    }

    /**
     * Gets the value of the bufferTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBufferTime() {
        return bufferTime;
    }

    /**
     * Sets the value of the bufferTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBufferTime(String value) {
        this.bufferTime = value;
    }

    /**
     * Gets the value of the trailerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrailerType() {
        return trailerType;
    }

    /**
     * Sets the value of the trailerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrailerType(String value) {
        this.trailerType = value;
    }

    /**
     * Gets the value of the containerList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the containerList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainerList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EdiContainersType }
     * 
     * 
     */
    public List<EdiContainersType> getContainerList() {
        if (containerList == null) {
            containerList = new ArrayList<EdiContainersType>();
        }
        return this.containerList;
    }

}
