//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 04:52:51 PM IST 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ediContainersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ediContainersType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="containerNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="forwardingAgent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gatePassNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sealNumber1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sealNumber2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="movementType" type="{http://etp.privasia.com/etp/service/schema}movementType" minOccurs="0"/&gt;
 *         &lt;element name="depotCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ediContainersType", propOrder = {
    "containerNumber",
    "forwardingAgent",
    "gatePassNumber",
    "sealNumber1",
    "sealNumber2",
    "movementType",
    "depotCode"
})
public class EdiContainersType {

    @XmlElement(required = true)
    protected String containerNumber;
    protected String forwardingAgent;
    protected String gatePassNumber;
    protected String sealNumber1;
    protected String sealNumber2;
    @XmlSchemaType(name = "string")
    protected MovementType movementType;
    protected String depotCode;

    /**
     * Gets the value of the containerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerNumber() {
        return containerNumber;
    }

    /**
     * Sets the value of the containerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerNumber(String value) {
        this.containerNumber = value;
    }

    /**
     * Gets the value of the forwardingAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardingAgent() {
        return forwardingAgent;
    }

    /**
     * Sets the value of the forwardingAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardingAgent(String value) {
        this.forwardingAgent = value;
    }

    /**
     * Gets the value of the gatePassNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatePassNumber() {
        return gatePassNumber;
    }

    /**
     * Sets the value of the gatePassNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatePassNumber(String value) {
        this.gatePassNumber = value;
    }

    /**
     * Gets the value of the sealNumber1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSealNumber1() {
        return sealNumber1;
    }

    /**
     * Sets the value of the sealNumber1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSealNumber1(String value) {
        this.sealNumber1 = value;
    }

    /**
     * Gets the value of the sealNumber2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSealNumber2() {
        return sealNumber2;
    }

    /**
     * Sets the value of the sealNumber2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSealNumber2(String value) {
        this.sealNumber2 = value;
    }

    /**
     * Gets the value of the movementType property.
     * 
     * @return
     *     possible object is
     *     {@link MovementType }
     *     
     */
    public MovementType getMovementType() {
        return movementType;
    }

    /**
     * Sets the value of the movementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MovementType }
     *     
     */
    public void setMovementType(MovementType value) {
        this.movementType = value;
    }

    /**
     * Gets the value of the depotCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepotCode() {
        return depotCode;
    }

    /**
     * Sets the value of the depotCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepotCode(String value) {
        this.depotCode = value;
    }

}
