//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 05:08:53 PM IST 
//


package com.privasia.scss.hpat.etp.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ediEdoRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ediEdoRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="scn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="blNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="line" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="containerList" type="{http://etp.privasia.com/etp/service/schema}ediContainersType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="emptyReturnLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="forwardingAgent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="unstuffingLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="edoExpiryDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lineDoNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="payerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="chequeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="chequeNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bankLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bypassValidation" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ediEdoRequestType", propOrder = {
    "scn",
    "blNumber",
    "line",
    "containerList",
    "emptyReturnLocation",
    "forwardingAgent",
    "remarks",
    "unstuffingLocation",
    "edoExpiryDateTime",
    "lineDoNumber",
    "payerName",
    "chequeType",
    "chequeNumber",
    "amount",
    "bank",
    "bankLocation",
    "bypassValidation"
})
public class EdiEdoRequestType {

    @XmlElement(required = true)
    protected String scn;
    @XmlElement(required = true)
    protected String blNumber;
    @XmlElement(required = true)
    protected String line;
    @XmlElement(required = true)
    protected List<EdiContainersType> containerList;
    protected String emptyReturnLocation;
    protected String forwardingAgent;
    protected String remarks;
    protected String unstuffingLocation;
    protected String edoExpiryDateTime;
    protected String lineDoNumber;
    protected String payerName;
    protected String chequeType;
    protected String chequeNumber;
    protected String amount;
    protected String bank;
    protected String bankLocation;
    protected boolean bypassValidation;

    /**
     * Gets the value of the scn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScn() {
        return scn;
    }

    /**
     * Sets the value of the scn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScn(String value) {
        this.scn = value;
    }

    /**
     * Gets the value of the blNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlNumber() {
        return blNumber;
    }

    /**
     * Sets the value of the blNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlNumber(String value) {
        this.blNumber = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine(String value) {
        this.line = value;
    }

    /**
     * Gets the value of the containerList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the containerList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainerList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EdiContainersType }
     * 
     * 
     */
    public List<EdiContainersType> getContainerList() {
        if (containerList == null) {
            containerList = new ArrayList<EdiContainersType>();
        }
        return this.containerList;
    }

    /**
     * Gets the value of the emptyReturnLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmptyReturnLocation() {
        return emptyReturnLocation;
    }

    /**
     * Sets the value of the emptyReturnLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmptyReturnLocation(String value) {
        this.emptyReturnLocation = value;
    }

    /**
     * Gets the value of the forwardingAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardingAgent() {
        return forwardingAgent;
    }

    /**
     * Sets the value of the forwardingAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardingAgent(String value) {
        this.forwardingAgent = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the unstuffingLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnstuffingLocation() {
        return unstuffingLocation;
    }

    /**
     * Sets the value of the unstuffingLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnstuffingLocation(String value) {
        this.unstuffingLocation = value;
    }

    /**
     * Gets the value of the edoExpiryDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdoExpiryDateTime() {
        return edoExpiryDateTime;
    }

    /**
     * Sets the value of the edoExpiryDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdoExpiryDateTime(String value) {
        this.edoExpiryDateTime = value;
    }

    /**
     * Gets the value of the lineDoNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineDoNumber() {
        return lineDoNumber;
    }

    /**
     * Sets the value of the lineDoNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineDoNumber(String value) {
        this.lineDoNumber = value;
    }

    /**
     * Gets the value of the payerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * Sets the value of the payerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerName(String value) {
        this.payerName = value;
    }

    /**
     * Gets the value of the chequeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChequeType() {
        return chequeType;
    }

    /**
     * Sets the value of the chequeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChequeType(String value) {
        this.chequeType = value;
    }

    /**
     * Gets the value of the chequeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChequeNumber() {
        return chequeNumber;
    }

    /**
     * Sets the value of the chequeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChequeNumber(String value) {
        this.chequeNumber = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the bank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBank() {
        return bank;
    }

    /**
     * Sets the value of the bank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBank(String value) {
        this.bank = value;
    }

    /**
     * Gets the value of the bankLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankLocation() {
        return bankLocation;
    }

    /**
     * Sets the value of the bankLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankLocation(String value) {
        this.bankLocation = value;
    }

    /**
     * Gets the value of the bypassValidation property.
     * 
     */
    public boolean isBypassValidation() {
        return bypassValidation;
    }

    /**
     * Sets the value of the bypassValidation property.
     * 
     */
    public void setBypassValidation(boolean value) {
        this.bypassValidation = value;
    }

}
