//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 06:36:43 PM SGT 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for edoDetailsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="edoDetailsResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="edoNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="createdDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="edoExpiryDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="blNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="splitBlNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="forwardingAgentCompany" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="forwardingAgentLedgerCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="edoStatus" type="{http://etp.privasia.com/etp/service/schema}edoStatusType"/&gt;
 *         &lt;element name="containerStatus" type="{http://etp.privasia.com/etp/service/schema}containerStatusType"/&gt;
 *         &lt;element name="mtReturnLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mtReturnLocationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="unStuffingLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="unStuffingLocationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "edoDetailsResponseType", propOrder = {
    "edoNumber",
    "createdDateTime",
    "edoExpiryDateTime",
    "blNumber",
    "splitBlNumber",
    "forwardingAgentCompany",
    "forwardingAgentLedgerCode",
    "edoStatus",
    "containerStatus",
    "mtReturnLocation",
    "mtReturnLocationCode",
    "unStuffingLocation",
    "unStuffingLocationCode"
})
public class EdoDetailsResponseType {

    @XmlElement(required = true)
    protected String edoNumber;
    @XmlElement(required = true)
    protected String createdDateTime;
    @XmlElement(required = true)
    protected String edoExpiryDateTime;
    @XmlElement(required = true)
    protected String blNumber;
    protected String splitBlNumber;
    @XmlElement(required = true)
    protected String forwardingAgentCompany;
    @XmlElement(required = true)
    protected String forwardingAgentLedgerCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EdoStatusType edoStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ContainerStatusType containerStatus;
    protected String mtReturnLocation;
    protected String mtReturnLocationCode;
    protected String unStuffingLocation;
    protected String unStuffingLocationCode;

    /**
     * Gets the value of the edoNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdoNumber() {
        return edoNumber;
    }

    /**
     * Sets the value of the edoNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdoNumber(String value) {
        this.edoNumber = value;
    }

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDateTime(String value) {
        this.createdDateTime = value;
    }

    /**
     * Gets the value of the edoExpiryDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdoExpiryDateTime() {
        return edoExpiryDateTime;
    }

    /**
     * Sets the value of the edoExpiryDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdoExpiryDateTime(String value) {
        this.edoExpiryDateTime = value;
    }

    /**
     * Gets the value of the blNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlNumber() {
        return blNumber;
    }

    /**
     * Sets the value of the blNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlNumber(String value) {
        this.blNumber = value;
    }

    /**
     * Gets the value of the splitBlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSplitBlNumber() {
        return splitBlNumber;
    }

    /**
     * Sets the value of the splitBlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSplitBlNumber(String value) {
        this.splitBlNumber = value;
    }

    /**
     * Gets the value of the forwardingAgentCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardingAgentCompany() {
        return forwardingAgentCompany;
    }

    /**
     * Sets the value of the forwardingAgentCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardingAgentCompany(String value) {
        this.forwardingAgentCompany = value;
    }

    /**
     * Gets the value of the forwardingAgentLedgerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardingAgentLedgerCode() {
        return forwardingAgentLedgerCode;
    }

    /**
     * Sets the value of the forwardingAgentLedgerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardingAgentLedgerCode(String value) {
        this.forwardingAgentLedgerCode = value;
    }

    /**
     * Gets the value of the edoStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EdoStatusType }
     *     
     */
    public EdoStatusType getEdoStatus() {
        return edoStatus;
    }

    /**
     * Sets the value of the edoStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdoStatusType }
     *     
     */
    public void setEdoStatus(EdoStatusType value) {
        this.edoStatus = value;
    }

    /**
     * Gets the value of the containerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ContainerStatusType }
     *     
     */
    public ContainerStatusType getContainerStatus() {
        return containerStatus;
    }

    /**
     * Sets the value of the containerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainerStatusType }
     *     
     */
    public void setContainerStatus(ContainerStatusType value) {
        this.containerStatus = value;
    }

    /**
     * Gets the value of the mtReturnLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtReturnLocation() {
        return mtReturnLocation;
    }

    /**
     * Sets the value of the mtReturnLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtReturnLocation(String value) {
        this.mtReturnLocation = value;
    }

    /**
     * Gets the value of the mtReturnLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtReturnLocationCode() {
        return mtReturnLocationCode;
    }

    /**
     * Sets the value of the mtReturnLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtReturnLocationCode(String value) {
        this.mtReturnLocationCode = value;
    }

    /**
     * Gets the value of the unStuffingLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnStuffingLocation() {
        return unStuffingLocation;
    }

    /**
     * Sets the value of the unStuffingLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnStuffingLocation(String value) {
        this.unStuffingLocation = value;
    }

    /**
     * Gets the value of the unStuffingLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnStuffingLocationCode() {
        return unStuffingLocationCode;
    }

    /**
     * Sets the value of the unStuffingLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnStuffingLocationCode(String value) {
        this.unStuffingLocationCode = value;
    }

}
