//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 04:52:51 PM IST 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hpatDetailsRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hpatDetailsRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="driverIc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="haulageCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="appointmnetDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hpatDetailsRequestType", propOrder = {
    "driverIc",
    "haulageCompanyCode",
    "appointmnetDate"
})
public class HpatDetailsRequestType {

    @XmlElement(required = true)
    protected String driverIc;
    @XmlElement(required = true)
    protected String haulageCompanyCode;
    @XmlElement(required = true)
    protected String appointmnetDate;

    /**
     * Gets the value of the driverIc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverIc() {
        return driverIc;
    }

    /**
     * Sets the value of the driverIc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverIc(String value) {
        this.driverIc = value;
    }

    /**
     * Gets the value of the haulageCompanyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaulageCompanyCode() {
        return haulageCompanyCode;
    }

    /**
     * Sets the value of the haulageCompanyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaulageCompanyCode(String value) {
        this.haulageCompanyCode = value;
    }

    /**
     * Gets the value of the appointmnetDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppointmnetDate() {
        return appointmnetDate;
    }

    /**
     * Sets the value of the appointmnetDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppointmnetDate(String value) {
        this.appointmnetDate = value;
    }

}
