//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 06:36:43 PM SGT 
//


package com.privasia.scss.hpat.etp.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hpatDetailsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hpatDetailsResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="refId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="driverIc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pmNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="trailerNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="trailerType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="appointmentDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="appointmentEndDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="buffer" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="haulageCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="createdDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="exportDetails" type="{http://etp.privasia.com/etp/service/schema}exportDetailsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="importDetails" type="{http://etp.privasia.com/etp/service/schema}importDetailsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="emptyPickupDetails" type="{http://etp.privasia.com/etp/service/schema}pickupReturnDetailsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="emptyReturnDetails" type="{http://etp.privasia.com/etp/service/schema}pickupReturnDetailsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hpatDetailsResponseType", propOrder = {
    "refId",
    "driverIc",
    "pmNo",
    "trailerNo",
    "trailerType",
    "appointmentDateTime",
    "appointmentEndDateTime",
    "buffer",
    "haulageCompanyCode",
    "createdDateTime",
    "exportDetails",
    "importDetails",
    "emptyPickupDetails",
    "emptyReturnDetails"
})
public class HpatDetailsResponseType {

    @XmlElement(required = true)
    protected String refId;
    @XmlElement(required = true)
    protected String driverIc;
    @XmlElement(required = true)
    protected String pmNo;
    @XmlElement(required = true)
    protected String trailerNo;
    @XmlElement(required = true)
    protected String trailerType;
    @XmlElement(required = true)
    protected String appointmentDateTime;
    protected String appointmentEndDateTime;
    protected int buffer;
    @XmlElement(required = true)
    protected String haulageCompanyCode;
    @XmlElement(required = true)
    protected String createdDateTime;
    @XmlElement(nillable = true)
    protected List<ExportDetailsType> exportDetails;
    @XmlElement(nillable = true)
    protected List<ImportDetailsType> importDetails;
    @XmlElement(nillable = true)
    protected List<PickupReturnDetailsType> emptyPickupDetails;
    @XmlElement(nillable = true)
    protected List<PickupReturnDetailsType> emptyReturnDetails;

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefId(String value) {
        this.refId = value;
    }

    /**
     * Gets the value of the driverIc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverIc() {
        return driverIc;
    }

    /**
     * Sets the value of the driverIc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverIc(String value) {
        this.driverIc = value;
    }

    /**
     * Gets the value of the pmNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmNo() {
        return pmNo;
    }

    /**
     * Sets the value of the pmNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmNo(String value) {
        this.pmNo = value;
    }

    /**
     * Gets the value of the trailerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrailerNo() {
        return trailerNo;
    }

    /**
     * Sets the value of the trailerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrailerNo(String value) {
        this.trailerNo = value;
    }

    /**
     * Gets the value of the trailerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrailerType() {
        return trailerType;
    }

    /**
     * Sets the value of the trailerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrailerType(String value) {
        this.trailerType = value;
    }

    /**
     * Gets the value of the appointmentDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppointmentDateTime() {
        return appointmentDateTime;
    }

    /**
     * Sets the value of the appointmentDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppointmentDateTime(String value) {
        this.appointmentDateTime = value;
    }

    /**
     * Gets the value of the appointmentEndDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppointmentEndDateTime() {
        return appointmentEndDateTime;
    }

    /**
     * Sets the value of the appointmentEndDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppointmentEndDateTime(String value) {
        this.appointmentEndDateTime = value;
    }

    /**
     * Gets the value of the buffer property.
     * 
     */
    public int getBuffer() {
        return buffer;
    }

    /**
     * Sets the value of the buffer property.
     * 
     */
    public void setBuffer(int value) {
        this.buffer = value;
    }

    /**
     * Gets the value of the haulageCompanyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaulageCompanyCode() {
        return haulageCompanyCode;
    }

    /**
     * Sets the value of the haulageCompanyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaulageCompanyCode(String value) {
        this.haulageCompanyCode = value;
    }

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedDateTime(String value) {
        this.createdDateTime = value;
    }

    /**
     * Gets the value of the exportDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exportDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExportDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExportDetailsType }
     * 
     * 
     */
    public List<ExportDetailsType> getExportDetails() {
        if (exportDetails == null) {
            exportDetails = new ArrayList<ExportDetailsType>();
        }
        return this.exportDetails;
    }

    /**
     * Gets the value of the importDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the importDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImportDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImportDetailsType }
     * 
     * 
     */
    public List<ImportDetailsType> getImportDetails() {
        if (importDetails == null) {
            importDetails = new ArrayList<ImportDetailsType>();
        }
        return this.importDetails;
    }

    /**
     * Gets the value of the emptyPickupDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emptyPickupDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmptyPickupDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PickupReturnDetailsType }
     * 
     * 
     */
    public List<PickupReturnDetailsType> getEmptyPickupDetails() {
        if (emptyPickupDetails == null) {
            emptyPickupDetails = new ArrayList<PickupReturnDetailsType>();
        }
        return this.emptyPickupDetails;
    }

    /**
     * Gets the value of the emptyReturnDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emptyReturnDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmptyReturnDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PickupReturnDetailsType }
     * 
     * 
     */
    public List<PickupReturnDetailsType> getEmptyReturnDetails() {
        if (emptyReturnDetails == null) {
            emptyReturnDetails = new ArrayList<PickupReturnDetailsType>();
        }
        return this.emptyReturnDetails;
    }

}
