//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 06:36:43 PM SGT 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mtOddGateOutContainerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mtOddGateOutContainerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pmHeadNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="containerNo1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="containerNo2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="callCardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="processDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="requestDateTimeCont1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="requestDateTimeCont2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="completeDateTimeCont1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="completeDateTimeCont2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gateOutDateTimeCont1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gateOutDateTimeCont2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://etp.privasia.com/etp/service/schema}txStatusType"/&gt;
 *         &lt;element name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mtOddGateOutContainerType", propOrder = {
    "pmHeadNumber",
    "containerNo1",
    "containerNo2",
    "callCardNumber",
    "processDateTime",
    "requestDateTimeCont1",
    "requestDateTimeCont2",
    "completeDateTimeCont1",
    "completeDateTimeCont2",
    "gateOutDateTimeCont1",
    "gateOutDateTimeCont2",
    "status",
    "errorMessage"
})
public class MtOddGateOutContainerType {

    @XmlElement(required = true)
    protected String pmHeadNumber;
    @XmlElement(required = true)
    protected String containerNo1;
    protected String containerNo2;
    protected String callCardNumber;
    protected String processDateTime;
    protected String requestDateTimeCont1;
    protected String requestDateTimeCont2;
    protected String completeDateTimeCont1;
    protected String completeDateTimeCont2;
    protected String gateOutDateTimeCont1;
    protected String gateOutDateTimeCont2;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TxStatusType status;
    protected String errorMessage;

    /**
     * Gets the value of the pmHeadNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmHeadNumber() {
        return pmHeadNumber;
    }

    /**
     * Sets the value of the pmHeadNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmHeadNumber(String value) {
        this.pmHeadNumber = value;
    }

    /**
     * Gets the value of the containerNo1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerNo1() {
        return containerNo1;
    }

    /**
     * Sets the value of the containerNo1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerNo1(String value) {
        this.containerNo1 = value;
    }

    /**
     * Gets the value of the containerNo2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerNo2() {
        return containerNo2;
    }

    /**
     * Sets the value of the containerNo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerNo2(String value) {
        this.containerNo2 = value;
    }

    /**
     * Gets the value of the callCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallCardNumber() {
        return callCardNumber;
    }

    /**
     * Sets the value of the callCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallCardNumber(String value) {
        this.callCardNumber = value;
    }

    /**
     * Gets the value of the processDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessDateTime() {
        return processDateTime;
    }

    /**
     * Sets the value of the processDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessDateTime(String value) {
        this.processDateTime = value;
    }

    /**
     * Gets the value of the requestDateTimeCont1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestDateTimeCont1() {
        return requestDateTimeCont1;
    }

    /**
     * Sets the value of the requestDateTimeCont1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestDateTimeCont1(String value) {
        this.requestDateTimeCont1 = value;
    }

    /**
     * Gets the value of the requestDateTimeCont2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestDateTimeCont2() {
        return requestDateTimeCont2;
    }

    /**
     * Sets the value of the requestDateTimeCont2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestDateTimeCont2(String value) {
        this.requestDateTimeCont2 = value;
    }

    /**
     * Gets the value of the completeDateTimeCont1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompleteDateTimeCont1() {
        return completeDateTimeCont1;
    }

    /**
     * Sets the value of the completeDateTimeCont1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompleteDateTimeCont1(String value) {
        this.completeDateTimeCont1 = value;
    }

    /**
     * Gets the value of the completeDateTimeCont2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompleteDateTimeCont2() {
        return completeDateTimeCont2;
    }

    /**
     * Sets the value of the completeDateTimeCont2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompleteDateTimeCont2(String value) {
        this.completeDateTimeCont2 = value;
    }

    /**
     * Gets the value of the gateOutDateTimeCont1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGateOutDateTimeCont1() {
        return gateOutDateTimeCont1;
    }

    /**
     * Sets the value of the gateOutDateTimeCont1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGateOutDateTimeCont1(String value) {
        this.gateOutDateTimeCont1 = value;
    }

    /**
     * Gets the value of the gateOutDateTimeCont2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGateOutDateTimeCont2() {
        return gateOutDateTimeCont2;
    }

    /**
     * Sets the value of the gateOutDateTimeCont2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGateOutDateTimeCont2(String value) {
        this.gateOutDateTimeCont2 = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link TxStatusType }
     *     
     */
    public TxStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxStatusType }
     *     
     */
    public void setStatus(TxStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

}
