//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 05:08:53 PM IST 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.privasia.scss.hpat.etp.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EtpProcessException_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "EtpProcessException");
    private final static QName _AuthenticateUserRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "authenticateUserRequest");
    private final static QName _AuthenticateUserResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "authenticateUserResponse");
    private final static QName _CancelEdiEdoRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "cancelEdiEdoRequest");
    private final static QName _CancelEdiEdoResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "cancelEdiEdoResponse");
    private final static QName _CreateEdiEdoRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "createEdiEdoRequest");
    private final static QName _CreateEdiEdoResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "createEdiEdoResponse");
    private final static QName _DemurrageRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "demurrageRequest");
    private final static QName _DemurrageResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "demurrageResponse");
    private final static QName _EdiBookingRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "ediBookingRequest");
    private final static QName _EdiBookingResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "ediBookingResponse");
    private final static QName _EdoDetailsRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "edoDetailsRequest");
    private final static QName _EdoDetailsResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "edoDetailsResponse");
    private final static QName _EdoExpiryForLineRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "edoExpiryForLineRequest");
    private final static QName _EdoExpiryForLineResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "edoExpiryForLineResponse");
    private final static QName _HpatDetailsRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "hpatDetailsRequest");
    private final static QName _HpatDetailsResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "hpatDetailsResponse");
    private final static QName _MtOddGateOutTransactionRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "mtOddGateOutTransactionRequest");
    private final static QName _MtOddGateOutTransactionResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "mtOddGateOutTransactionResponse");
    private final static QName _PendingSsrDetailsRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "pendingSsrDetailsRequest");
    private final static QName _PendingSsrDetailsResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "pendingSsrDetailsResponse");
    private final static QName _ReplaceEdiEdoRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "replaceEdiEdoRequest");
    private final static QName _ReplaceEdiEdoResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "replaceEdiEdoResponse");
    private final static QName _SendSsrBillDetailsRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "sendSsrBillDetailsRequest");
    private final static QName _SendSsrBillDetailsResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "sendSsrBillDetailsResponse");
    private final static QName _SsrDetailsRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "ssrDetailsRequest");
    private final static QName _SsrDetailsResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "ssrDetailsResponse");
    private final static QName _SsrFlagRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "ssrFlagRequest");
    private final static QName _SsrFlagResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "ssrFlagResponse");
    private final static QName _UpdateDrayageMovementDetailsRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "updateDrayageMovementDetailsRequest");
    private final static QName _UpdateDrayageMovementDetailsResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "updateDrayageMovementDetailsResponse");
    private final static QName _UpdateEGatepassDetailsRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "updateEGatepassDetailsRequest");
    private final static QName _UpdateEGatepassDetailsResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "updateEGatepassDetailsResponse");
    private final static QName _UpdateEdiEdoRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "updateEdiEdoRequest");
    private final static QName _UpdateEdiEdoResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "updateEdiEdoResponse");
    private final static QName _UpdateHpatStatusRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "updateHpatStatusRequest");
    private final static QName _UpdateHpatStatusResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "updateHpatStatusResponse");
    private final static QName _UpdateSolasForScssGateInRequest_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "updateSolasForScssGateInRequest");
    private final static QName _UpdateSolasForScssGateInResponse_QNAME = new QName("http://etp.privasia.com/etp/service/schema", "updateSolasForScssGateInResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.privasia.scss.hpat.etp.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EtpProcessExceptionType }
     * 
     */
    public EtpProcessExceptionType createEtpProcessExceptionType() {
        return new EtpProcessExceptionType();
    }

    /**
     * Create an instance of {@link AuthenticateUserRequestType }
     * 
     */
    public AuthenticateUserRequestType createAuthenticateUserRequestType() {
        return new AuthenticateUserRequestType();
    }

    /**
     * Create an instance of {@link AuthenticateUserResponseType }
     * 
     */
    public AuthenticateUserResponseType createAuthenticateUserResponseType() {
        return new AuthenticateUserResponseType();
    }

    /**
     * Create an instance of {@link CancelEdiEdoRequestType }
     * 
     */
    public CancelEdiEdoRequestType createCancelEdiEdoRequestType() {
        return new CancelEdiEdoRequestType();
    }

    /**
     * Create an instance of {@link EdiEdoResponseType }
     * 
     */
    public EdiEdoResponseType createEdiEdoResponseType() {
        return new EdiEdoResponseType();
    }

    /**
     * Create an instance of {@link EdiEdoRequestType }
     * 
     */
    public EdiEdoRequestType createEdiEdoRequestType() {
        return new EdiEdoRequestType();
    }

    /**
     * Create an instance of {@link DemurrageRequestType }
     * 
     */
    public DemurrageRequestType createDemurrageRequestType() {
        return new DemurrageRequestType();
    }

    /**
     * Create an instance of {@link DemurrageResponseType }
     * 
     */
    public DemurrageResponseType createDemurrageResponseType() {
        return new DemurrageResponseType();
    }

    /**
     * Create an instance of {@link EdiBookingRequestType }
     * 
     */
    public EdiBookingRequestType createEdiBookingRequestType() {
        return new EdiBookingRequestType();
    }

    /**
     * Create an instance of {@link EdiBookingResponseType }
     * 
     */
    public EdiBookingResponseType createEdiBookingResponseType() {
        return new EdiBookingResponseType();
    }

    /**
     * Create an instance of {@link EdoDetailsRequestType }
     * 
     */
    public EdoDetailsRequestType createEdoDetailsRequestType() {
        return new EdoDetailsRequestType();
    }

    /**
     * Create an instance of {@link EdoDetailsResponseType }
     * 
     */
    public EdoDetailsResponseType createEdoDetailsResponseType() {
        return new EdoDetailsResponseType();
    }

    /**
     * Create an instance of {@link EdoExpiryForLineRequestType }
     * 
     */
    public EdoExpiryForLineRequestType createEdoExpiryForLineRequestType() {
        return new EdoExpiryForLineRequestType();
    }

    /**
     * Create an instance of {@link EdoExpiryForLineResponseType }
     * 
     */
    public EdoExpiryForLineResponseType createEdoExpiryForLineResponseType() {
        return new EdoExpiryForLineResponseType();
    }

    /**
     * Create an instance of {@link HpatDetailsRequestType }
     * 
     */
    public HpatDetailsRequestType createHpatDetailsRequestType() {
        return new HpatDetailsRequestType();
    }

    /**
     * Create an instance of {@link HpatDetailsListResponseType }
     * 
     */
    public HpatDetailsListResponseType createHpatDetailsListResponseType() {
        return new HpatDetailsListResponseType();
    }

    /**
     * Create an instance of {@link MtOddGateOutTransactionRequestType }
     * 
     */
    public MtOddGateOutTransactionRequestType createMtOddGateOutTransactionRequestType() {
        return new MtOddGateOutTransactionRequestType();
    }

    /**
     * Create an instance of {@link MtOddGateOutTransactionResponseType }
     * 
     */
    public MtOddGateOutTransactionResponseType createMtOddGateOutTransactionResponseType() {
        return new MtOddGateOutTransactionResponseType();
    }

    /**
     * Create an instance of {@link PendingSsrDetailsRequestType }
     * 
     */
    public PendingSsrDetailsRequestType createPendingSsrDetailsRequestType() {
        return new PendingSsrDetailsRequestType();
    }

    /**
     * Create an instance of {@link PendingSsrDetailsResponseType }
     * 
     */
    public PendingSsrDetailsResponseType createPendingSsrDetailsResponseType() {
        return new PendingSsrDetailsResponseType();
    }

    /**
     * Create an instance of {@link SendSsrBillDetailsRequestType }
     * 
     */
    public SendSsrBillDetailsRequestType createSendSsrBillDetailsRequestType() {
        return new SendSsrBillDetailsRequestType();
    }

    /**
     * Create an instance of {@link SendSsrBillDetailsResponseType }
     * 
     */
    public SendSsrBillDetailsResponseType createSendSsrBillDetailsResponseType() {
        return new SendSsrBillDetailsResponseType();
    }

    /**
     * Create an instance of {@link SsrDetailsRequestType }
     * 
     */
    public SsrDetailsRequestType createSsrDetailsRequestType() {
        return new SsrDetailsRequestType();
    }

    /**
     * Create an instance of {@link SsrDetailsResponseType }
     * 
     */
    public SsrDetailsResponseType createSsrDetailsResponseType() {
        return new SsrDetailsResponseType();
    }

    /**
     * Create an instance of {@link SsrFlagRequestType }
     * 
     */
    public SsrFlagRequestType createSsrFlagRequestType() {
        return new SsrFlagRequestType();
    }

    /**
     * Create an instance of {@link SsrFlagResponseType }
     * 
     */
    public SsrFlagResponseType createSsrFlagResponseType() {
        return new SsrFlagResponseType();
    }

    /**
     * Create an instance of {@link UpdateDrayageMovementDetailsRequestType }
     * 
     */
    public UpdateDrayageMovementDetailsRequestType createUpdateDrayageMovementDetailsRequestType() {
        return new UpdateDrayageMovementDetailsRequestType();
    }

    /**
     * Create an instance of {@link UpdateDrayageMovementDetailsResponseType }
     * 
     */
    public UpdateDrayageMovementDetailsResponseType createUpdateDrayageMovementDetailsResponseType() {
        return new UpdateDrayageMovementDetailsResponseType();
    }

    /**
     * Create an instance of {@link UpdateEGatepassDetailsRequestType }
     * 
     */
    public UpdateEGatepassDetailsRequestType createUpdateEGatepassDetailsRequestType() {
        return new UpdateEGatepassDetailsRequestType();
    }

    /**
     * Create an instance of {@link UpdateEGatepassDetailsResponseType }
     * 
     */
    public UpdateEGatepassDetailsResponseType createUpdateEGatepassDetailsResponseType() {
        return new UpdateEGatepassDetailsResponseType();
    }

    /**
     * Create an instance of {@link UpdateHpatStatusRequestType }
     * 
     */
    public UpdateHpatStatusRequestType createUpdateHpatStatusRequestType() {
        return new UpdateHpatStatusRequestType();
    }

    /**
     * Create an instance of {@link UpdateHpatStatusResponseType }
     * 
     */
    public UpdateHpatStatusResponseType createUpdateHpatStatusResponseType() {
        return new UpdateHpatStatusResponseType();
    }

    /**
     * Create an instance of {@link UpdateSolasForScssGateInRequestType }
     * 
     */
    public UpdateSolasForScssGateInRequestType createUpdateSolasForScssGateInRequestType() {
        return new UpdateSolasForScssGateInRequestType();
    }

    /**
     * Create an instance of {@link UpdateSolasForScssGateInResponseType }
     * 
     */
    public UpdateSolasForScssGateInResponseType createUpdateSolasForScssGateInResponseType() {
        return new UpdateSolasForScssGateInResponseType();
    }

    /**
     * Create an instance of {@link EdiEdoContainerResponseType }
     * 
     */
    public EdiEdoContainerResponseType createEdiEdoContainerResponseType() {
        return new EdiEdoContainerResponseType();
    }

    /**
     * Create an instance of {@link EdiBookingItemResponseType }
     * 
     */
    public EdiBookingItemResponseType createEdiBookingItemResponseType() {
        return new EdiBookingItemResponseType();
    }

    /**
     * Create an instance of {@link EdiBookingContainerResponseType }
     * 
     */
    public EdiBookingContainerResponseType createEdiBookingContainerResponseType() {
        return new EdiBookingContainerResponseType();
    }

    /**
     * Create an instance of {@link EdiContainersType }
     * 
     */
    public EdiContainersType createEdiContainersType() {
        return new EdiContainersType();
    }

    /**
     * Create an instance of {@link ContainerDemurrageType }
     * 
     */
    public ContainerDemurrageType createContainerDemurrageType() {
        return new ContainerDemurrageType();
    }

    /**
     * Create an instance of {@link SsrContainersType }
     * 
     */
    public SsrContainersType createSsrContainersType() {
        return new SsrContainersType();
    }

    /**
     * Create an instance of {@link SsrBillHeaderType }
     * 
     */
    public SsrBillHeaderType createSsrBillHeaderType() {
        return new SsrBillHeaderType();
    }

    /**
     * Create an instance of {@link SsrBillDetailsType }
     * 
     */
    public SsrBillDetailsType createSsrBillDetailsType() {
        return new SsrBillDetailsType();
    }

    /**
     * Create an instance of {@link UserHaulierCompaniesType }
     * 
     */
    public UserHaulierCompaniesType createUserHaulierCompaniesType() {
        return new UserHaulierCompaniesType();
    }

    /**
     * Create an instance of {@link MtOddGateOutContainerType }
     * 
     */
    public MtOddGateOutContainerType createMtOddGateOutContainerType() {
        return new MtOddGateOutContainerType();
    }

    /**
     * Create an instance of {@link ImportDetailsType }
     * 
     */
    public ImportDetailsType createImportDetailsType() {
        return new ImportDetailsType();
    }

    /**
     * Create an instance of {@link RequestContainerList }
     * 
     */
    public RequestContainerList createRequestContainerList() {
        return new RequestContainerList();
    }

    /**
     * Create an instance of {@link ExportDetailsType }
     * 
     */
    public ExportDetailsType createExportDetailsType() {
        return new ExportDetailsType();
    }

    /**
     * Create an instance of {@link HpatDetailsResponseType }
     * 
     */
    public HpatDetailsResponseType createHpatDetailsResponseType() {
        return new HpatDetailsResponseType();
    }

    /**
     * Create an instance of {@link PickupReturnDetailsType }
     * 
     */
    public PickupReturnDetailsType createPickupReturnDetailsType() {
        return new PickupReturnDetailsType();
    }

    /**
     * Create an instance of {@link EdiBookingType }
     * 
     */
    public EdiBookingType createEdiBookingType() {
        return new EdiBookingType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EtpProcessExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "EtpProcessException")
    public JAXBElement<EtpProcessExceptionType> createEtpProcessException(EtpProcessExceptionType value) {
        return new JAXBElement<EtpProcessExceptionType>(_EtpProcessException_QNAME, EtpProcessExceptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticateUserRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "authenticateUserRequest")
    public JAXBElement<AuthenticateUserRequestType> createAuthenticateUserRequest(AuthenticateUserRequestType value) {
        return new JAXBElement<AuthenticateUserRequestType>(_AuthenticateUserRequest_QNAME, AuthenticateUserRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticateUserResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "authenticateUserResponse")
    public JAXBElement<AuthenticateUserResponseType> createAuthenticateUserResponse(AuthenticateUserResponseType value) {
        return new JAXBElement<AuthenticateUserResponseType>(_AuthenticateUserResponse_QNAME, AuthenticateUserResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelEdiEdoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "cancelEdiEdoRequest")
    public JAXBElement<CancelEdiEdoRequestType> createCancelEdiEdoRequest(CancelEdiEdoRequestType value) {
        return new JAXBElement<CancelEdiEdoRequestType>(_CancelEdiEdoRequest_QNAME, CancelEdiEdoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdiEdoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "cancelEdiEdoResponse")
    public JAXBElement<EdiEdoResponseType> createCancelEdiEdoResponse(EdiEdoResponseType value) {
        return new JAXBElement<EdiEdoResponseType>(_CancelEdiEdoResponse_QNAME, EdiEdoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdiEdoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "createEdiEdoRequest")
    public JAXBElement<EdiEdoRequestType> createCreateEdiEdoRequest(EdiEdoRequestType value) {
        return new JAXBElement<EdiEdoRequestType>(_CreateEdiEdoRequest_QNAME, EdiEdoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdiEdoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "createEdiEdoResponse")
    public JAXBElement<EdiEdoResponseType> createCreateEdiEdoResponse(EdiEdoResponseType value) {
        return new JAXBElement<EdiEdoResponseType>(_CreateEdiEdoResponse_QNAME, EdiEdoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DemurrageRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "demurrageRequest")
    public JAXBElement<DemurrageRequestType> createDemurrageRequest(DemurrageRequestType value) {
        return new JAXBElement<DemurrageRequestType>(_DemurrageRequest_QNAME, DemurrageRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DemurrageResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "demurrageResponse")
    public JAXBElement<DemurrageResponseType> createDemurrageResponse(DemurrageResponseType value) {
        return new JAXBElement<DemurrageResponseType>(_DemurrageResponse_QNAME, DemurrageResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdiBookingRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "ediBookingRequest")
    public JAXBElement<EdiBookingRequestType> createEdiBookingRequest(EdiBookingRequestType value) {
        return new JAXBElement<EdiBookingRequestType>(_EdiBookingRequest_QNAME, EdiBookingRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdiBookingResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "ediBookingResponse")
    public JAXBElement<EdiBookingResponseType> createEdiBookingResponse(EdiBookingResponseType value) {
        return new JAXBElement<EdiBookingResponseType>(_EdiBookingResponse_QNAME, EdiBookingResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdoDetailsRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "edoDetailsRequest")
    public JAXBElement<EdoDetailsRequestType> createEdoDetailsRequest(EdoDetailsRequestType value) {
        return new JAXBElement<EdoDetailsRequestType>(_EdoDetailsRequest_QNAME, EdoDetailsRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdoDetailsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "edoDetailsResponse")
    public JAXBElement<EdoDetailsResponseType> createEdoDetailsResponse(EdoDetailsResponseType value) {
        return new JAXBElement<EdoDetailsResponseType>(_EdoDetailsResponse_QNAME, EdoDetailsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdoExpiryForLineRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "edoExpiryForLineRequest")
    public JAXBElement<EdoExpiryForLineRequestType> createEdoExpiryForLineRequest(EdoExpiryForLineRequestType value) {
        return new JAXBElement<EdoExpiryForLineRequestType>(_EdoExpiryForLineRequest_QNAME, EdoExpiryForLineRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdoExpiryForLineResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "edoExpiryForLineResponse")
    public JAXBElement<EdoExpiryForLineResponseType> createEdoExpiryForLineResponse(EdoExpiryForLineResponseType value) {
        return new JAXBElement<EdoExpiryForLineResponseType>(_EdoExpiryForLineResponse_QNAME, EdoExpiryForLineResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HpatDetailsRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "hpatDetailsRequest")
    public JAXBElement<HpatDetailsRequestType> createHpatDetailsRequest(HpatDetailsRequestType value) {
        return new JAXBElement<HpatDetailsRequestType>(_HpatDetailsRequest_QNAME, HpatDetailsRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HpatDetailsListResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "hpatDetailsResponse")
    public JAXBElement<HpatDetailsListResponseType> createHpatDetailsResponse(HpatDetailsListResponseType value) {
        return new JAXBElement<HpatDetailsListResponseType>(_HpatDetailsResponse_QNAME, HpatDetailsListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MtOddGateOutTransactionRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "mtOddGateOutTransactionRequest")
    public JAXBElement<MtOddGateOutTransactionRequestType> createMtOddGateOutTransactionRequest(MtOddGateOutTransactionRequestType value) {
        return new JAXBElement<MtOddGateOutTransactionRequestType>(_MtOddGateOutTransactionRequest_QNAME, MtOddGateOutTransactionRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MtOddGateOutTransactionResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "mtOddGateOutTransactionResponse")
    public JAXBElement<MtOddGateOutTransactionResponseType> createMtOddGateOutTransactionResponse(MtOddGateOutTransactionResponseType value) {
        return new JAXBElement<MtOddGateOutTransactionResponseType>(_MtOddGateOutTransactionResponse_QNAME, MtOddGateOutTransactionResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PendingSsrDetailsRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "pendingSsrDetailsRequest")
    public JAXBElement<PendingSsrDetailsRequestType> createPendingSsrDetailsRequest(PendingSsrDetailsRequestType value) {
        return new JAXBElement<PendingSsrDetailsRequestType>(_PendingSsrDetailsRequest_QNAME, PendingSsrDetailsRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PendingSsrDetailsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "pendingSsrDetailsResponse")
    public JAXBElement<PendingSsrDetailsResponseType> createPendingSsrDetailsResponse(PendingSsrDetailsResponseType value) {
        return new JAXBElement<PendingSsrDetailsResponseType>(_PendingSsrDetailsResponse_QNAME, PendingSsrDetailsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdiEdoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "replaceEdiEdoRequest")
    public JAXBElement<EdiEdoRequestType> createReplaceEdiEdoRequest(EdiEdoRequestType value) {
        return new JAXBElement<EdiEdoRequestType>(_ReplaceEdiEdoRequest_QNAME, EdiEdoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdiEdoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "replaceEdiEdoResponse")
    public JAXBElement<EdiEdoResponseType> createReplaceEdiEdoResponse(EdiEdoResponseType value) {
        return new JAXBElement<EdiEdoResponseType>(_ReplaceEdiEdoResponse_QNAME, EdiEdoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSsrBillDetailsRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "sendSsrBillDetailsRequest")
    public JAXBElement<SendSsrBillDetailsRequestType> createSendSsrBillDetailsRequest(SendSsrBillDetailsRequestType value) {
        return new JAXBElement<SendSsrBillDetailsRequestType>(_SendSsrBillDetailsRequest_QNAME, SendSsrBillDetailsRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSsrBillDetailsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "sendSsrBillDetailsResponse")
    public JAXBElement<SendSsrBillDetailsResponseType> createSendSsrBillDetailsResponse(SendSsrBillDetailsResponseType value) {
        return new JAXBElement<SendSsrBillDetailsResponseType>(_SendSsrBillDetailsResponse_QNAME, SendSsrBillDetailsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SsrDetailsRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "ssrDetailsRequest")
    public JAXBElement<SsrDetailsRequestType> createSsrDetailsRequest(SsrDetailsRequestType value) {
        return new JAXBElement<SsrDetailsRequestType>(_SsrDetailsRequest_QNAME, SsrDetailsRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SsrDetailsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "ssrDetailsResponse")
    public JAXBElement<SsrDetailsResponseType> createSsrDetailsResponse(SsrDetailsResponseType value) {
        return new JAXBElement<SsrDetailsResponseType>(_SsrDetailsResponse_QNAME, SsrDetailsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SsrFlagRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "ssrFlagRequest")
    public JAXBElement<SsrFlagRequestType> createSsrFlagRequest(SsrFlagRequestType value) {
        return new JAXBElement<SsrFlagRequestType>(_SsrFlagRequest_QNAME, SsrFlagRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SsrFlagResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "ssrFlagResponse")
    public JAXBElement<SsrFlagResponseType> createSsrFlagResponse(SsrFlagResponseType value) {
        return new JAXBElement<SsrFlagResponseType>(_SsrFlagResponse_QNAME, SsrFlagResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateDrayageMovementDetailsRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "updateDrayageMovementDetailsRequest")
    public JAXBElement<UpdateDrayageMovementDetailsRequestType> createUpdateDrayageMovementDetailsRequest(UpdateDrayageMovementDetailsRequestType value) {
        return new JAXBElement<UpdateDrayageMovementDetailsRequestType>(_UpdateDrayageMovementDetailsRequest_QNAME, UpdateDrayageMovementDetailsRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateDrayageMovementDetailsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "updateDrayageMovementDetailsResponse")
    public JAXBElement<UpdateDrayageMovementDetailsResponseType> createUpdateDrayageMovementDetailsResponse(UpdateDrayageMovementDetailsResponseType value) {
        return new JAXBElement<UpdateDrayageMovementDetailsResponseType>(_UpdateDrayageMovementDetailsResponse_QNAME, UpdateDrayageMovementDetailsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateEGatepassDetailsRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "updateEGatepassDetailsRequest")
    public JAXBElement<UpdateEGatepassDetailsRequestType> createUpdateEGatepassDetailsRequest(UpdateEGatepassDetailsRequestType value) {
        return new JAXBElement<UpdateEGatepassDetailsRequestType>(_UpdateEGatepassDetailsRequest_QNAME, UpdateEGatepassDetailsRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateEGatepassDetailsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "updateEGatepassDetailsResponse")
    public JAXBElement<UpdateEGatepassDetailsResponseType> createUpdateEGatepassDetailsResponse(UpdateEGatepassDetailsResponseType value) {
        return new JAXBElement<UpdateEGatepassDetailsResponseType>(_UpdateEGatepassDetailsResponse_QNAME, UpdateEGatepassDetailsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdiEdoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "updateEdiEdoRequest")
    public JAXBElement<EdiEdoRequestType> createUpdateEdiEdoRequest(EdiEdoRequestType value) {
        return new JAXBElement<EdiEdoRequestType>(_UpdateEdiEdoRequest_QNAME, EdiEdoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdiEdoResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "updateEdiEdoResponse")
    public JAXBElement<EdiEdoResponseType> createUpdateEdiEdoResponse(EdiEdoResponseType value) {
        return new JAXBElement<EdiEdoResponseType>(_UpdateEdiEdoResponse_QNAME, EdiEdoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateHpatStatusRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "updateHpatStatusRequest")
    public JAXBElement<UpdateHpatStatusRequestType> createUpdateHpatStatusRequest(UpdateHpatStatusRequestType value) {
        return new JAXBElement<UpdateHpatStatusRequestType>(_UpdateHpatStatusRequest_QNAME, UpdateHpatStatusRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateHpatStatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "updateHpatStatusResponse")
    public JAXBElement<UpdateHpatStatusResponseType> createUpdateHpatStatusResponse(UpdateHpatStatusResponseType value) {
        return new JAXBElement<UpdateHpatStatusResponseType>(_UpdateHpatStatusResponse_QNAME, UpdateHpatStatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateSolasForScssGateInRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "updateSolasForScssGateInRequest")
    public JAXBElement<UpdateSolasForScssGateInRequestType> createUpdateSolasForScssGateInRequest(UpdateSolasForScssGateInRequestType value) {
        return new JAXBElement<UpdateSolasForScssGateInRequestType>(_UpdateSolasForScssGateInRequest_QNAME, UpdateSolasForScssGateInRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateSolasForScssGateInResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://etp.privasia.com/etp/service/schema", name = "updateSolasForScssGateInResponse")
    public JAXBElement<UpdateSolasForScssGateInResponseType> createUpdateSolasForScssGateInResponse(UpdateSolasForScssGateInResponseType value) {
        return new JAXBElement<UpdateSolasForScssGateInResponseType>(_UpdateSolasForScssGateInResponse_QNAME, UpdateSolasForScssGateInResponseType.class, null, value);
    }

}
