//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 05:08:53 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://etp.privasia.com/etp/service/schema")
package com.privasia.scss.hpat.etp.service;
