//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 06:36:43 PM SGT 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pickupReturnDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pickupReturnDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="containerNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="containerType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="containerLength" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="oddLocation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pickupReturnDetailsType", propOrder = {
    "containerNo",
    "containerType",
    "containerLength",
    "oddLocation"
})
public class PickupReturnDetailsType {

    @XmlElement(required = true)
    protected String containerNo;
    @XmlElement(required = true)
    protected String containerType;
    @XmlElement(required = true)
    protected String containerLength;
    @XmlElement(required = true)
    protected String oddLocation;

    /**
     * Gets the value of the containerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerNo() {
        return containerNo;
    }

    /**
     * Sets the value of the containerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerNo(String value) {
        this.containerNo = value;
    }

    /**
     * Gets the value of the containerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerType() {
        return containerType;
    }

    /**
     * Sets the value of the containerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerType(String value) {
        this.containerType = value;
    }

    /**
     * Gets the value of the containerLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerLength() {
        return containerLength;
    }

    /**
     * Sets the value of the containerLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerLength(String value) {
        this.containerLength = value;
    }

    /**
     * Gets the value of the oddLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOddLocation() {
        return oddLocation;
    }

    /**
     * Sets the value of the oddLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOddLocation(String value) {
        this.oddLocation = value;
    }

}
