//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 06:36:43 PM SGT 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ssrBillDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ssrBillDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ssrRefNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="containerNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="containerLength" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fclLcl" type="{http://etp.privasia.com/etp/service/schema}fclLclType" minOccurs="0"/&gt;
 *         &lt;element name="fullEmpty" type="{http://etp.privasia.com/etp/service/schema}fullEmptyType" minOccurs="0"/&gt;
 *         &lt;element name="visitNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="scn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="voyage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vesselName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vesselCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="eta" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="inHandlingId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ssrBillDetailsType", propOrder = {
    "ssrRefNumber",
    "containerNo",
    "containerLength",
    "fclLcl",
    "fullEmpty",
    "visitNo",
    "scn",
    "voyage",
    "vesselName",
    "vesselCode",
    "eta",
    "remarks",
    "inHandlingId"
})
public class SsrBillDetailsType {

    @XmlElement(required = true)
    protected String ssrRefNumber;
    @XmlElement(required = true)
    protected String containerNo;
    @XmlElement(required = true)
    protected String containerLength;
    @XmlSchemaType(name = "string")
    protected FclLclType fclLcl;
    @XmlSchemaType(name = "string")
    protected FullEmptyType fullEmpty;
    protected String visitNo;
    @XmlElement(required = true)
    protected String scn;
    @XmlElement(required = true)
    protected String voyage;
    @XmlElement(required = true)
    protected String vesselName;
    @XmlElement(required = true)
    protected String vesselCode;
    @XmlElement(required = true)
    protected String eta;
    @XmlElement(required = true)
    protected String remarks;
    protected int inHandlingId;

    /**
     * Gets the value of the ssrRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsrRefNumber() {
        return ssrRefNumber;
    }

    /**
     * Sets the value of the ssrRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsrRefNumber(String value) {
        this.ssrRefNumber = value;
    }

    /**
     * Gets the value of the containerNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerNo() {
        return containerNo;
    }

    /**
     * Sets the value of the containerNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerNo(String value) {
        this.containerNo = value;
    }

    /**
     * Gets the value of the containerLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerLength() {
        return containerLength;
    }

    /**
     * Sets the value of the containerLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerLength(String value) {
        this.containerLength = value;
    }

    /**
     * Gets the value of the fclLcl property.
     * 
     * @return
     *     possible object is
     *     {@link FclLclType }
     *     
     */
    public FclLclType getFclLcl() {
        return fclLcl;
    }

    /**
     * Sets the value of the fclLcl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FclLclType }
     *     
     */
    public void setFclLcl(FclLclType value) {
        this.fclLcl = value;
    }

    /**
     * Gets the value of the fullEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link FullEmptyType }
     *     
     */
    public FullEmptyType getFullEmpty() {
        return fullEmpty;
    }

    /**
     * Sets the value of the fullEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullEmptyType }
     *     
     */
    public void setFullEmpty(FullEmptyType value) {
        this.fullEmpty = value;
    }

    /**
     * Gets the value of the visitNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitNo() {
        return visitNo;
    }

    /**
     * Sets the value of the visitNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitNo(String value) {
        this.visitNo = value;
    }

    /**
     * Gets the value of the scn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScn() {
        return scn;
    }

    /**
     * Sets the value of the scn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScn(String value) {
        this.scn = value;
    }

    /**
     * Gets the value of the voyage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoyage() {
        return voyage;
    }

    /**
     * Sets the value of the voyage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoyage(String value) {
        this.voyage = value;
    }

    /**
     * Gets the value of the vesselName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselName() {
        return vesselName;
    }

    /**
     * Sets the value of the vesselName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselName(String value) {
        this.vesselName = value;
    }

    /**
     * Gets the value of the vesselCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselCode() {
        return vesselCode;
    }

    /**
     * Sets the value of the vesselCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselCode(String value) {
        this.vesselCode = value;
    }

    /**
     * Gets the value of the eta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEta() {
        return eta;
    }

    /**
     * Sets the value of the eta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEta(String value) {
        this.eta = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the inHandlingId property.
     * 
     */
    public int getInHandlingId() {
        return inHandlingId;
    }

    /**
     * Sets the value of the inHandlingId property.
     * 
     */
    public void setInHandlingId(int value) {
        this.inHandlingId = value;
    }

}
