//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 04:52:51 PM IST 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ssrBillHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ssrBillHeaderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ssrRefNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="line" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="agent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ssrSubmitDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ssrStatus" type="{http://etp.privasia.com/etp/service/schema}txStatusType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ssrBillHeaderType", propOrder = {
    "ssrRefNumber",
    "line",
    "agent",
    "ssrSubmitDate",
    "remarks",
    "ssrStatus"
})
public class SsrBillHeaderType {

    @XmlElement(required = true)
    protected String ssrRefNumber;
    @XmlElement(required = true)
    protected String line;
    @XmlElement(required = true)
    protected String agent;
    @XmlElement(required = true)
    protected String ssrSubmitDate;
    protected String remarks;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TxStatusType ssrStatus;

    /**
     * Gets the value of the ssrRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsrRefNumber() {
        return ssrRefNumber;
    }

    /**
     * Sets the value of the ssrRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsrRefNumber(String value) {
        this.ssrRefNumber = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine(String value) {
        this.line = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgent(String value) {
        this.agent = value;
    }

    /**
     * Gets the value of the ssrSubmitDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsrSubmitDate() {
        return ssrSubmitDate;
    }

    /**
     * Sets the value of the ssrSubmitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsrSubmitDate(String value) {
        this.ssrSubmitDate = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the ssrStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TxStatusType }
     *     
     */
    public TxStatusType getSsrStatus() {
        return ssrStatus;
    }

    /**
     * Sets the value of the ssrStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxStatusType }
     *     
     */
    public void setSsrStatus(TxStatusType value) {
        this.ssrStatus = value;
    }

}
