//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 06:36:43 PM SGT 
//


package com.privasia.scss.hpat.etp.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ssrDetailsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ssrDetailsResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ssrNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="opsType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="agent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contactNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ledgerCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="serviceType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="scn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vesselName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="voyage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vesselEta" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ssrCreatedDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ssrModifiedDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ssrRequestedBy" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="approvedBy" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="approvedDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bookingDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="bookingNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="locationFrom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="locationTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="returnDepot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="serviceCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="containerDetails" type="{http://etp.privasia.com/etp/service/schema}ssrContainersType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="terminalComments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="orderRefNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="agentRefNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ssrDetailsResponseType", propOrder = {
    "ssrNumber",
    "opsType",
    "agent",
    "email",
    "contactNumber",
    "ledgerCode",
    "serviceType",
    "scn",
    "vesselName",
    "voyage",
    "vesselEta",
    "ssrCreatedDateTime",
    "ssrModifiedDateTime",
    "ssrRequestedBy",
    "approvedBy",
    "approvedDateTime",
    "bookingDateTime",
    "bookingNumber",
    "locationFrom",
    "locationTo",
    "returnDepot",
    "serviceCode",
    "containerDetails",
    "terminalComments",
    "orderRefNumber",
    "agentRefNumber"
})
public class SsrDetailsResponseType {

    @XmlElement(required = true)
    protected String ssrNumber;
    protected String opsType;
    @XmlElement(required = true)
    protected String agent;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String contactNumber;
    @XmlElement(required = true)
    protected String ledgerCode;
    @XmlElement(required = true)
    protected String serviceType;
    @XmlElement(required = true)
    protected String scn;
    @XmlElement(required = true)
    protected String vesselName;
    @XmlElement(required = true)
    protected String voyage;
    @XmlElement(required = true)
    protected String vesselEta;
    @XmlElement(required = true)
    protected String ssrCreatedDateTime;
    protected String ssrModifiedDateTime;
    @XmlElement(required = true)
    protected String ssrRequestedBy;
    @XmlElement(required = true)
    protected String approvedBy;
    @XmlElement(required = true)
    protected String approvedDateTime;
    protected String bookingDateTime;
    protected String bookingNumber;
    protected String locationFrom;
    protected String locationTo;
    protected String returnDepot;
    @XmlElement(required = true)
    protected String serviceCode;
    @XmlElement(nillable = true)
    protected List<SsrContainersType> containerDetails;
    protected String terminalComments;
    @XmlElement(required = true)
    protected String orderRefNumber;
    protected String agentRefNumber;

    /**
     * Gets the value of the ssrNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsrNumber() {
        return ssrNumber;
    }

    /**
     * Sets the value of the ssrNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsrNumber(String value) {
        this.ssrNumber = value;
    }

    /**
     * Gets the value of the opsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpsType() {
        return opsType;
    }

    /**
     * Sets the value of the opsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpsType(String value) {
        this.opsType = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgent(String value) {
        this.agent = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the contactNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * Sets the value of the contactNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactNumber(String value) {
        this.contactNumber = value;
    }

    /**
     * Gets the value of the ledgerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLedgerCode() {
        return ledgerCode;
    }

    /**
     * Sets the value of the ledgerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLedgerCode(String value) {
        this.ledgerCode = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the scn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScn() {
        return scn;
    }

    /**
     * Sets the value of the scn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScn(String value) {
        this.scn = value;
    }

    /**
     * Gets the value of the vesselName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselName() {
        return vesselName;
    }

    /**
     * Sets the value of the vesselName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselName(String value) {
        this.vesselName = value;
    }

    /**
     * Gets the value of the voyage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoyage() {
        return voyage;
    }

    /**
     * Sets the value of the voyage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoyage(String value) {
        this.voyage = value;
    }

    /**
     * Gets the value of the vesselEta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselEta() {
        return vesselEta;
    }

    /**
     * Sets the value of the vesselEta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselEta(String value) {
        this.vesselEta = value;
    }

    /**
     * Gets the value of the ssrCreatedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsrCreatedDateTime() {
        return ssrCreatedDateTime;
    }

    /**
     * Sets the value of the ssrCreatedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsrCreatedDateTime(String value) {
        this.ssrCreatedDateTime = value;
    }

    /**
     * Gets the value of the ssrModifiedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsrModifiedDateTime() {
        return ssrModifiedDateTime;
    }

    /**
     * Sets the value of the ssrModifiedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsrModifiedDateTime(String value) {
        this.ssrModifiedDateTime = value;
    }

    /**
     * Gets the value of the ssrRequestedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsrRequestedBy() {
        return ssrRequestedBy;
    }

    /**
     * Sets the value of the ssrRequestedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsrRequestedBy(String value) {
        this.ssrRequestedBy = value;
    }

    /**
     * Gets the value of the approvedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedBy() {
        return approvedBy;
    }

    /**
     * Sets the value of the approvedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedBy(String value) {
        this.approvedBy = value;
    }

    /**
     * Gets the value of the approvedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedDateTime() {
        return approvedDateTime;
    }

    /**
     * Sets the value of the approvedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedDateTime(String value) {
        this.approvedDateTime = value;
    }

    /**
     * Gets the value of the bookingDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingDateTime() {
        return bookingDateTime;
    }

    /**
     * Sets the value of the bookingDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingDateTime(String value) {
        this.bookingDateTime = value;
    }

    /**
     * Gets the value of the bookingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingNumber() {
        return bookingNumber;
    }

    /**
     * Sets the value of the bookingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingNumber(String value) {
        this.bookingNumber = value;
    }

    /**
     * Gets the value of the locationFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationFrom() {
        return locationFrom;
    }

    /**
     * Sets the value of the locationFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationFrom(String value) {
        this.locationFrom = value;
    }

    /**
     * Gets the value of the locationTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationTo() {
        return locationTo;
    }

    /**
     * Sets the value of the locationTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationTo(String value) {
        this.locationTo = value;
    }

    /**
     * Gets the value of the returnDepot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnDepot() {
        return returnDepot;
    }

    /**
     * Sets the value of the returnDepot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnDepot(String value) {
        this.returnDepot = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the containerDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the containerDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainerDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SsrContainersType }
     * 
     * 
     */
    public List<SsrContainersType> getContainerDetails() {
        if (containerDetails == null) {
            containerDetails = new ArrayList<SsrContainersType>();
        }
        return this.containerDetails;
    }

    /**
     * Gets the value of the terminalComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalComments() {
        return terminalComments;
    }

    /**
     * Sets the value of the terminalComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalComments(String value) {
        this.terminalComments = value;
    }

    /**
     * Gets the value of the orderRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderRefNumber() {
        return orderRefNumber;
    }

    /**
     * Sets the value of the orderRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderRefNumber(String value) {
        this.orderRefNumber = value;
    }

    /**
     * Gets the value of the agentRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentRefNumber() {
        return agentRefNumber;
    }

    /**
     * Sets the value of the agentRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentRefNumber(String value) {
        this.agentRefNumber = value;
    }

}
