//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 06:36:43 PM SGT 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ssrFlagResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ssrFlagResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ssrFlag" type="{http://etp.privasia.com/etp/service/schema}ssrFlagType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ssrFlagResponseType", propOrder = {
    "ssrFlag"
})
public class SsrFlagResponseType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected SsrFlagType ssrFlag;

    /**
     * Gets the value of the ssrFlag property.
     * 
     * @return
     *     possible object is
     *     {@link SsrFlagType }
     *     
     */
    public SsrFlagType getSsrFlag() {
        return ssrFlag;
    }

    /**
     * Sets the value of the ssrFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link SsrFlagType }
     *     
     */
    public void setSsrFlag(SsrFlagType value) {
        this.ssrFlag = value;
    }

}
