//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 06:36:43 PM SGT 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateEGatepassDetailsRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateEGatepassDetailsRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="etpRefId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="conatinerNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="haulierName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="haulierCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="scn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gatepassNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateEGatepassDetailsRequestType", propOrder = {
    "etpRefId",
    "conatinerNumber",
    "haulierName",
    "haulierCode",
    "scn",
    "gatepassNumber"
})
public class UpdateEGatepassDetailsRequestType {

    @XmlElement(required = true)
    protected String etpRefId;
    @XmlElement(required = true)
    protected String conatinerNumber;
    @XmlElement(required = true)
    protected String haulierName;
    @XmlElement(required = true)
    protected String haulierCode;
    @XmlElement(required = true)
    protected String scn;
    @XmlElement(required = true)
    protected String gatepassNumber;

    /**
     * Gets the value of the etpRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEtpRefId() {
        return etpRefId;
    }

    /**
     * Sets the value of the etpRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEtpRefId(String value) {
        this.etpRefId = value;
    }

    /**
     * Gets the value of the conatinerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConatinerNumber() {
        return conatinerNumber;
    }

    /**
     * Sets the value of the conatinerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConatinerNumber(String value) {
        this.conatinerNumber = value;
    }

    /**
     * Gets the value of the haulierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaulierName() {
        return haulierName;
    }

    /**
     * Sets the value of the haulierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaulierName(String value) {
        this.haulierName = value;
    }

    /**
     * Gets the value of the haulierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaulierCode() {
        return haulierCode;
    }

    /**
     * Sets the value of the haulierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaulierCode(String value) {
        this.haulierCode = value;
    }

    /**
     * Gets the value of the scn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScn() {
        return scn;
    }

    /**
     * Sets the value of the scn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScn(String value) {
        this.scn = value;
    }

    /**
     * Gets the value of the gatepassNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatepassNumber() {
        return gatepassNumber;
    }

    /**
     * Sets the value of the gatepassNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatepassNumber(String value) {
        this.gatepassNumber = value;
    }

}
