//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 06:36:43 PM SGT 
//


package com.privasia.scss.hpat.etp.service;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for updateSolasForScssGateInRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateSolasForScssGateInRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="solasDetId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="terminalVgm" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="weighingMethod" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="weighingStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vgmReferenceNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vgmDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="vgmFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vgmFileDate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="withnessName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="withnessNric" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="variance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="grossWeight" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="terminalMgw" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="isTolerance" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateSolasForScssGateInRequestType", propOrder = {
    "solasDetId",
    "terminalVgm",
    "weighingMethod",
    "weighingStation",
    "vgmReferenceNo",
    "vgmDate",
    "vgmFileName",
    "vgmFileDate",
    "withnessName",
    "withnessNric",
    "variance",
    "grossWeight",
    "terminalMgw",
    "isTolerance"
})
public class UpdateSolasForScssGateInRequestType {

    @XmlElement(required = true)
    protected String solasDetId;
    protected Integer terminalVgm;
    protected Integer weighingMethod;
    protected String weighingStation;
    protected String vgmReferenceNo;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vgmDate;
    protected String vgmFileName;
    protected byte[] vgmFileDate;
    protected String withnessName;
    protected String withnessNric;
    protected BigDecimal variance;
    protected Integer grossWeight;
    protected Integer terminalMgw;
    protected Boolean isTolerance;

    /**
     * Gets the value of the solasDetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolasDetId() {
        return solasDetId;
    }

    /**
     * Sets the value of the solasDetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolasDetId(String value) {
        this.solasDetId = value;
    }

    /**
     * Gets the value of the terminalVgm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTerminalVgm() {
        return terminalVgm;
    }

    /**
     * Sets the value of the terminalVgm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTerminalVgm(Integer value) {
        this.terminalVgm = value;
    }

    /**
     * Gets the value of the weighingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeighingMethod() {
        return weighingMethod;
    }

    /**
     * Sets the value of the weighingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeighingMethod(Integer value) {
        this.weighingMethod = value;
    }

    /**
     * Gets the value of the weighingStation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeighingStation() {
        return weighingStation;
    }

    /**
     * Sets the value of the weighingStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeighingStation(String value) {
        this.weighingStation = value;
    }

    /**
     * Gets the value of the vgmReferenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVgmReferenceNo() {
        return vgmReferenceNo;
    }

    /**
     * Sets the value of the vgmReferenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVgmReferenceNo(String value) {
        this.vgmReferenceNo = value;
    }

    /**
     * Gets the value of the vgmDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVgmDate() {
        return vgmDate;
    }

    /**
     * Sets the value of the vgmDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVgmDate(XMLGregorianCalendar value) {
        this.vgmDate = value;
    }

    /**
     * Gets the value of the vgmFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVgmFileName() {
        return vgmFileName;
    }

    /**
     * Sets the value of the vgmFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVgmFileName(String value) {
        this.vgmFileName = value;
    }

    /**
     * Gets the value of the vgmFileDate property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getVgmFileDate() {
        return vgmFileDate;
    }

    /**
     * Sets the value of the vgmFileDate property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setVgmFileDate(byte[] value) {
        this.vgmFileDate = value;
    }

    /**
     * Gets the value of the withnessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWithnessName() {
        return withnessName;
    }

    /**
     * Sets the value of the withnessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWithnessName(String value) {
        this.withnessName = value;
    }

    /**
     * Gets the value of the withnessNric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWithnessNric() {
        return withnessNric;
    }

    /**
     * Sets the value of the withnessNric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWithnessNric(String value) {
        this.withnessNric = value;
    }

    /**
     * Gets the value of the variance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVariance() {
        return variance;
    }

    /**
     * Sets the value of the variance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVariance(BigDecimal value) {
        this.variance = value;
    }

    /**
     * Gets the value of the grossWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGrossWeight() {
        return grossWeight;
    }

    /**
     * Sets the value of the grossWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGrossWeight(Integer value) {
        this.grossWeight = value;
    }

    /**
     * Gets the value of the terminalMgw property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTerminalMgw() {
        return terminalMgw;
    }

    /**
     * Sets the value of the terminalMgw property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTerminalMgw(Integer value) {
        this.terminalMgw = value;
    }

    /**
     * Gets the value of the isTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsTolerance() {
        return isTolerance;
    }

    /**
     * Sets the value of the isTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTolerance(Boolean value) {
        this.isTolerance = value;
    }

}
