//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.13 at 06:36:43 PM SGT 
//


package com.privasia.scss.hpat.etp.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userHaulierCompaniesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userHaulierCompaniesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="haulierCompany" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="haulierCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="haulierLedger" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userHaulierCompaniesType", propOrder = {
    "haulierCompany",
    "haulierCode",
    "haulierLedger"
})
public class UserHaulierCompaniesType {

    @XmlElement(required = true)
    protected String haulierCompany;
    @XmlElement(required = true)
    protected String haulierCode;
    @XmlElement(required = true)
    protected String haulierLedger;

    /**
     * Gets the value of the haulierCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaulierCompany() {
        return haulierCompany;
    }

    /**
     * Sets the value of the haulierCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaulierCompany(String value) {
        this.haulierCompany = value;
    }

    /**
     * Gets the value of the haulierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaulierCode() {
        return haulierCode;
    }

    /**
     * Sets the value of the haulierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaulierCode(String value) {
        this.haulierCode = value;
    }

    /**
     * Gets the value of the haulierLedger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHaulierLedger() {
        return haulierLedger;
    }

    /**
     * Sets the value of the haulierLedger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHaulierLedger(String value) {
        this.haulierLedger = value;
    }

}
